name: Run tests

on: 
  push:
    branches:
      - main
  pull_request:
    types: [labeled]
    branches:
      - main

jobs:
  job1:
    if: github.event_name == 'push' || contains(github.event.label.name, 'runchecks')
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo A comment $COMMENT on PR $NUMBER. Should run 
        env:
          NUMBER: ${{ github.event.issue.number }}
          COMMENT: ${{ github.event.comment.body }}
  job2:
    if: github.event_name == 'push' || contains(github.event.label.name, 'runchecks')
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo A comment $COMMENT on PR $NUMBER
        env:
          NUMBER: ${{ github.event.issue.number }}
          COMMENT: ${{ github.event.comment.body }}