name: Run tests

on: issue_comment

jobs:
  pr_commented:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo A comment $COMMENT on PR $NUMBER
        env:
          NUMBER: ${{ github.event.issue.number }}
          COMMENT: ${{ github.event.comment.body }}